name: Run checks

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: PHP ${{ matrix.php-versions }} Test ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.0', '7.1', '7.2', '7.3']
        composer-flags: ['', '--prefer-lowest']
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --prefer-stable ${{ matrix.composer-flags }}

      - name: Run test suite
        run: composer test
